version: "3.9"

services:
  djangoapp:
    build:
      context: .
    expose:
      - 8000
    volumes:
      - staticfiles:/pytudo_docker/staticfiles
      - media:/pytudo_docker/media
      - logs:/pytudo_docker/logs
    env_file:
      - .env
    depends_on:
      - postgres_prod_db

  nginx:
    build: ./nginx
    volumes:
      - staticfiles:/pytudo_docker/staticfiles
      - media:/pytudo_docker/media
      - nginx_logs:/pytudo_docker/nginx/logs
    ports:
      - "80:80"
    depends_on:
      - djangoapp

  postgres_prod_db:
    image: postgres:16.2-alpine3.18
    container_name: postgres_prod_db
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    env_file:
      - .env



volumes:
  postgres_prod_data:
  staticfiles:
  media:
  logs:
  nginx_logs: