# Generated by Django 4.2 on 2024-01-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtos_altura_produtos_frete_gratis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
