# Generated by Django 4.2 on 2023-04-24 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0003_produtos_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.CharField(blank=True, choices=[('1', 'Pessimo'), ('2', 'Ruim'), ('3', 'Bom'), ('4', 'Otimo'), ('5', 'Perfeito')], max_length=1, null=True)),
                ('comentario', models.TextField()),
                ('produto', models.ManyToManyField(blank=True, to='produtos.produtos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
