# Generated by Django 4.2 on 2023-04-24 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='produto',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='produto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos'),
            preserve_default=False,
        ),
    ]
