# Generated by Django 4.2 on 2023-04-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produtos_marca_alter_produtos_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='cor',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
