# Generated by Django 4.2 on 2023-05-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_produtos_data_atualizacao_produtos_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='preco_de_custo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
