# Generated by Django 4.2 on 2023-05-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_produtos_preco_de_custo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='preco_de_custo',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
