# Generated by Django 4.2 on 2023-05-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_alter_produtos_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
