# Generated by Django 4.2 on 2023-05-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_remove_produtos_foto_imagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
