# Generated by Django 4.2 on 2023-06-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_produtos_imagem_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='cor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
