# Generated by Django 4.2 on 2023-06-09 05:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0018_alter_produtos_cor_alter_produtos_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 6, 9, 5, 18, 17, 620438, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='estrelas',
            field=models.CharField(choices=[('1', 'Pessimo'), ('2', 'Ruim'), ('3', 'Bom'), ('4', 'Otimo'), ('5', 'Perfeito')], default=datetime.datetime(2023, 6, 9, 5, 20, 40, 309014, tzinfo=datetime.timezone.utc), max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
