# Generated by Django 4.2 on 2023-06-09 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuarios_data_de_nascimento'),
        ('produtos', '0019_avaliacao_data_atualizacao_avaliacao_data_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuarios'),
        ),
    ]
