# Generated by Django 4.2 on 2023-06-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0021_banner_destacadoshome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
