# Generated by Django 4.2 on 2023-06-20 04:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0022_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAlteracaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('detalhes', models.TextField()),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produtos')),
            ],
        ),
    ]
