# Generated by Django 4.2 on 2023-06-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0023_registroalteracaoproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroalteracaoproduto',
            name='produto',
            field=models.ForeignKey(default=39, on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.produtos'),
            preserve_default=False,
        ),
    ]
