# Generated by Django 4.2 on 2023-09-27 04:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0026_alter_avaliacao_comentario_alter_avaliacao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='especificacao',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
