# Generated by Django 4.2 on 2023-09-27 16:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0027_produtos_especificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='especificacao',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
