# Generated by Django 4.2 on 2023-12-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='informacoes_adicionais',
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_de_pagamento',
            field=models.CharField(choices=[('creditCard', 'creditCard'), ('boleto', 'boleto'), ('pix', 'pix')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('AUTHORIZED', 'AUTHORIZED'), ('IN_ANALYSIS', 'IN_ANALYSIS'), ('DECLINED', 'DECLINED'), ('PAID', 'PAID'), ('CANCELED', 'CANCELED')], default='CURRENT', max_length=100),
        ),
    ]
