# Generated by Django 4.2 on 2023-12-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_pedido_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mensagem_de_erro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
