# Generated by Django 4.2 on 2023-12-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_pedido_mensagem_de_erro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='link_pagamento',
            field=models.URLField(blank=True, null=True),
        ),
    ]
