# Generated by Django 4.2 on 2023-12-12 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='historicocupomdesconto',
            name='venda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.pedido'),
        ),
        migrations.DeleteModel(
            name='ItemVenda',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
