# Generated by Django 4.2 on 2023-04-22 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0003_produtos_quantidade'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='adicionar_no_carrinho', to='produtos.produtos'),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
