# Generated by Django 4.2 on 2023-07-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0025_alter_registroalteracaoproduto_produto'),
        ('vendas', '0004_rename_carrinho_listadesejo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadesejo',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='adicionar_na_lista_desejo', to='produtos.produtos'),
        ),
    ]
