# Generated by Django 4.2 on 2023-07-20 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0006_alter_listadesejo_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupomDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_desconto', models.CharField(choices=[('P', 'Porcentagem'), ('R', 'Reais')], max_length=1)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.PositiveIntegerField()),
                ('inicio_validade', models.DateTimeField()),
                ('fim_validade', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='venda',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricoCupomDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda')),
            ],
        ),
    ]
