# Generated by Django 4.2 on 2023-07-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_cupomdesconto_alter_venda_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupomdesconto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
