# Generated by Django 4.2 on 2023-07-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_cupomdesconto_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupomdesconto',
            name='desconto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cupomdesconto',
            name='fim_validade',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cupomdesconto',
            name='inicio_validade',
            field=models.DateField(),
        ),
    ]
