# Generated by Django 4.1.3 on 2022-12-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=35)),
                ('senha', models.CharField(max_length=64)),
                ('celular', models.IntegerField()),
                ('endereco', models.CharField(max_length=50)),
                ('numero_endereco', models.IntegerField()),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
    ]
