# Generated by Django 4.1.3 on 2022-12-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='celular',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='numero_endereco',
            field=models.CharField(max_length=10),
        ),
    ]
