# Generated by Django 4.1.3 on 2022-12-27 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_alter_usuarios_celular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='senha',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
