# Generated by Django 4.1.3 on 2023-01-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuarios_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='complemento',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
