# Generated by Django 4.2 on 2023-05-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuarios_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
