# Generated by Django 4.2 on 2023-05-16 03:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuarios_data_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
