# Generated by Django 4.2 on 2023-05-16 15:54

import cpf_field.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0007_alter_usuarios_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cpf',
            field=cpf_field.models.CPFField(default='41186436859', max_length=14, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
