# Generated by Django 4.2 on 2023-05-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuarios_celular_alter_usuarios_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
