# Generated by Django 4.2 on 2023-05-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_usuarios_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='data_de_nascimento',
            field=models.DateField(default=None, null=True),
        ),
    ]
