# Generated by Django 4.2 on 2023-05-23 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_usuarios_data_de_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='data_de_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
