# Generated by Django 4.2 on 2023-06-23 02:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuarios_data_de_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAlteracaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('detalhes', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuarios')),
            ],
        ),
    ]
