# Generated by Django 4.2 on 2023-06-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
