# Generated by Django 4.2 on 2023-08-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_banner_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
